[package]
name = "sync-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.138"

base = { path = "../base" }
cluster = {path = "../cluster/"}
tokio = { version = "1", features = ["full"] }
