[package]
name = "cluster"
version = "0.1.0"
edition = "2021"

[dependencies]
base = {path = "../base/"}
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
[[bin]]
name = "sync_main"
path = "src/bin/sync_main.rs"
